import {brand} from '@/lib/products';
import {siteConfig} from '@/lib/site-config';
import {Arrow,Brand,WhatsAppIcon,WhatsAppLink} from './shared';

export function BrandNavbar({message=brand.message}:{message?:string}) {
  const links=[['Home','/'],['Products','/#products'],['Expert Advisor','/ea/auric-grid-v5/'],['Indicators','/indicators/'],['FAQ','/#faq']];
  return <><a className="skip-link" href="#main">Lewati ke konten</a><header className="navbar brand-navbar" id="navbar"><div className="nav-inner"><Brand master/><nav className="desktop-nav" aria-label="Navigasi utama">{links.map(([label,url])=><a href={url} key={label}>{label}</a>)}</nav><WhatsAppLink message={message} className="nav-cta">WhatsApp <Arrow diagonal/></WhatsAppLink><button id="menu-toggle" className="menu-toggle" aria-label="Buka menu" aria-controls="mobile-menu" aria-expanded="false"><span/><span/></button></div><nav id="mobile-menu" className="mobile-nav" aria-label="Navigasi mobile" hidden>{links.map(([label,url])=><a key={label} href={url}>{label}<Arrow/></a>)}</nav></header></>;
}

export function BrandRisk(){return <section id="risk" className="risk-disclosure container brand-risk"><div><span className="risk-symbol">!</span><h2>Tools membantu proses. Risiko tetap ada.</h2></div><p>Trading memiliki risiko kehilangan sebagian atau seluruh modal. Indicator adalah alat bantu analisis; signal dan momentum tidak menjamin ketepatan entry atau keuntungan. Expert Advisor juga dapat mengalami floating loss dan drawdown. Hasil pengujian tidak menjamin performa mendatang. Keputusan trading dan pengelolaan risiko tetap berada pada pengguna.</p></section>}

export function BrandContact({name,message=brand.message}:{name?:string;message?:string}){return <section className="contact-cta container brand-contact"><div><span className="eyebrow">LET’S TALK</span><h2>{name?`Kenali ${name} lebih jauh.`:'Temukan tools untuk proses trading Anda.'}</h2><p>{name?'Tanyakan detail indikator, akses, dan cara pemasangannya kepada admin.':'Hubungi admin untuk detail Expert Advisor, indikator, dan layanan pemasangan.'}</p></div><WhatsAppLink message={message} className="button outline">Hubungi admin <Arrow diagonal/></WhatsAppLink></section>}

export function BrandFooter({message=brand.message}:{message?:string}){return <><footer className="footer container"><div className="footer-top"><div><Brand master/><p>{brand.tagline}</p></div><nav aria-label="Navigasi footer"><a href="/">Home</a><a href="/ea/auric-grid-v5/">Expert Advisor</a><a href="/indicators/">Indicators</a><a href="/#faq">FAQ</a><a href="#risk">Risk Disclosure</a></nav><WhatsAppLink message={message} className="footer-contact">{siteConfig.whatsappDisplay}<Arrow diagonal/></WhatsAppLink></div><p className="privacy-note">Privasi: tidak ada form data pribadi, analytics, atau pelacak pihak ketiga di website ini. Saat menghubungi admin, kebijakan privasi WhatsApp berlaku.</p><div className="footer-bottom"><span>© 2026 AURIC. All rights reserved.</span><span>Trading involves risk.</span></div></footer><WhatsAppLink message={message} className="floating-wa"><span className="sr-only">Hubungi admin melalui WhatsApp</span><WhatsAppIcon/></WhatsAppLink></>}
