import {brand,products,indicators,indicatorPurchase} from '@/lib/products';
import {siteConfig} from '@/lib/site-config';
import {Arrow,SectionLabel,WhatsAppLink} from './shared';
import {ProductScreenshot} from './ProductScreenshot';

export function BrandHero(){return <section className="brand-hero"><div className="hero-grid"/><div className="container brand-hero-layout"><div className="brand-hero-copy"><p className="eyebrow">TRADING SYSTEMS · MARKET ANALYSIS</p><h1>AURIC<span className="brand-period">.</span></h1><h2>Trading technology.<br/><span>Built for the market.</span></h2><p className="brand-hero-description">Trading systems dan market-analysis tools yang dirancang untuk membantu trader menganalisis dan mengelola market secara lebih terstruktur.</p><div className="hero-actions"><a className="button gold" href="#products">Explore products <Arrow/></a><a className="button text-button" href="/indicators/">View indicators <Arrow/></a></div><div className="hero-platforms"><span>METATRADER 5</span><span>TRADINGVIEW</span></div></div><div className="brand-engine"><img src={siteConfig.robotImage} srcSet="/assets/auric-robot-v2-640.webp 640w, /assets/auric-robot-v2.webp 1024w" sizes="(max-width: 640px) 100vw, 620px" width="1024" height="1024" alt="Robot AURIC dengan detail gunmetal, emas dan cyan sebagai identitas brand" fetchPriority="high"/><span className="engine-label">AURIC / TRADING TECHNOLOGY</span><div className="engine-index"><span>01 / AUTOMATION</span><span>02 / MARKET ANALYSIS</span></div></div></div></section>}

export function Ecosystem(){return <section className="section container ecosystem" id="products"><div className="section-heading two-col"><div><SectionLabel number="01">OUR ECOSYSTEM</SectionLabel><h2>Dua pendekatan.<br/><span>Satu keluarga AURIC.</span></h2></div><p className="intro-copy">Pilih tools sesuai cara Anda bekerja: mengelola proses secara otomatis atau membaca market untuk mengambil keputusan sendiri.</p></div><div className="ecosystem-layout"><a className="ecosystem-ea" href="/ea/auric-grid-v5/"><span className="eyebrow">CATEGORY 01 / AUTOMATED TRADING</span><h3>AURIC GRID V5</h3><p className="category-tagline">Automated XAUUSD Trading System</p><p>Expert Advisor untuk MetaTrader 5 yang dirancang untuk mengelola proses trading secara otomatis.</p><span className="category-link">Explore EA <Arrow/></span><span className="category-meta">MT5 / XAUUSD / VPS INCLUDED</span></a><a className="ecosystem-indicators" href="/indicators/"><span className="eyebrow">CATEGORY 02 / MARKET ANALYSIS</span><h3>AURIC INDICATORS</h3><p className="category-tagline">Smart Money & Momentum Trading Tools</p><p>Trading indicators untuk membantu membaca market structure, momentum, area penting, dan setup trading.</p><span className="category-link">Explore indicators <Arrow/></span><span className="category-meta">TRADINGVIEW / MANUAL ANALYSIS</span></a></div></section>}

export function FeaturedProducts(){return <section className="featured section container"><div className="section-heading"><SectionLabel number="02">FEATURED PRODUCTS</SectionLabel><h2>Tools dengan <span>peran yang jelas.</span></h2></div><div className="product-ledger">{products.map((p,i)=><article className="product-ledger-row" key={p.slug}><span className="ledger-number">0{i+1}</span><div className="ledger-visual"><img src={i===0?siteConfig.robotImage:p.screenshot.src} width={i===0?1024:p.screenshot.width} height={i===0?1024:p.screenshot.height} alt={i===0?'Visual brand AURIC GRID V5':p.screenshot.alt} loading="lazy"/></div><div className="ledger-copy"><span className="eyebrow">{p.productType==='ea'?'EXPERT ADVISOR':'TRADING INDICATOR'}</span><h3><a href={p.path}>{p.productName}</a></h3><p>{p.tagline}</p><div className="product-tags"><span>{p.platform}</span><span>{i===0?'XAUUSD · Automated Trading':i===1?'Structure · Entry · Liquidity':'Momentum · Candle'}</span></div>{p.productType==='indicator'&&<p className="ledger-offer"><strong>{p.price}</strong><span>{indicatorPurchase.model}</span></p>}</div><a className="ledger-link" href={p.path}>{p.productType==='indicator'?'Lihat produk':'Explore product'} <Arrow/></a></article>)}</div></section>}

export function IndicatorShowcase(){return <section className="analysis-showcase"><div className="container section"><div className="section-heading"><SectionLabel number="03">SEE THE TOOLS IN ACTION</SectionLabel><h2>Konteks market.<br/><span>Langsung pada chart.</span></h2></div><div className="showcase-editorial"><ProductScreenshot product={indicators[0]} id="home-smc"/><div className="showcase-copy"><span className="eyebrow">AURIC SMC SIGNAL</span><h3>Market structure,<br/>in context.</h3><p>BOS, CHoCH, dan informasi liquidity membantu membaca perubahan struktur market. Area entry dan visual TP / SL memberi konteks tambahan pada setup.</p><a className="inline-link" href={indicators[0].path}>Jelajahi SMC Signal <Arrow/></a></div></div><div className="showcase-editorial reversed"><div className="showcase-copy"><span className="eyebrow">AURIC MOMENTUM</span><h3>Perhatikan kekuatan<br/>pergerakan candle.</h3><p>Momentum candle memberi konteks tambahan saat membaca pergerakan harga. Gunakan bersama area penting dan rencana trading Anda.</p><a className="inline-link" href={indicators[1].path}>Jelajahi Momentum <Arrow/></a></div><ProductScreenshot product={indicators[1]} id="home-momentum"/></div><p className="showcase-note">Screenshot adalah cuplikan tampilan produk, bukan rekomendasi transaksi atau jaminan hasil. Label dan kondisi chart mengikuti referensi asli.</p></div></section>}

export function TwoWays(){return <section className="section container two-ways"><SectionLabel number="04">TWO WAYS TO TRADE WITH AURIC</SectionLabel><h2>Sesuaikan dengan <span>cara Anda trading.</span></h2><div className="ways-layout"><article><span className="eyebrow">MANUAL ANALYSIS</span><h3>AURIC INDICATORS</h3><p>Tools untuk trader yang tetap ingin melakukan analisis dan mengambil keputusan trading sendiri.</p><p className="model-note">{indicatorPurchase.price} per indikator · Sekali bayar<br/>Akses seumur hidup · Full source code</p><a href="/indicators/" className="inline-link">Market analysis tools <Arrow/></a></article><article><span className="eyebrow">AUTOMATED TRADING</span><h3>AURIC GRID V5</h3><p>Expert Advisor yang menjalankan proses trading berdasarkan sistem otomatis. Pengguna tetap menentukan keputusan penggunaan dan risiko modal.</p><p className="model-note">{siteConfig.price} / {siteConfig.rentalDays} Hari · Sewa EA<br/>VPS &amp; setup termasuk · Tanpa source code EA</p><a href="/ea/auric-grid-v5/" className="inline-link">Automated trading system <Arrow/></a></article></div></section>}

export function WhyAuric(){return <section className="why-auric container section"><div><SectionLabel number="05">WHY AURIC</SectionLabel><h2>Proses yang jelas.<br/><span>Informasi yang terbuka.</span></h2></div><div className="why-points"><article><span>01</span><div><h3>Tujuan penggunaan yang spesifik</h3><p>Automation dan market analysis memiliki peran masing-masing, dengan informasi produk yang mudah dibandingkan.</p></div></article><article><span>02</span><div><h3>Tampilan produk asli</h3><p>Screenshot chart dan data pengujian EA ditampilkan sebagai bahan evaluasi, termasuk drawdown pada pengujian EA.</p></div></article><article><span>03</span><div><h3>Komunikasi langsung</h3><p>Tanyakan detail produk dan pemasangan kepada admin sebelum menentukan pilihan.</p></div></article></div></section>}

export function ProductChoice(){return <section className="product-choice container"><span className="eyebrow">FIND YOUR TOOLS</span><h2>Mulai dari kebutuhan Anda.</h2><div><a className="button gold" href="/ea/auric-grid-v5/">Explore Expert Advisor <Arrow/></a><a className="button outline" href="/indicators/">Explore indicators <Arrow/></a></div></section>}

export function BrandFAQ(){const items=[['Apa itu AURIC?','AURIC adalah brand trading technology dengan dua kategori produk: Expert Advisor untuk proses trading otomatis dan indicators untuk membantu analisis market.'],['Apa perbedaan EA dan indicator?','Expert Advisor menjalankan proses trading berdasarkan aturan sistem di MetaTrader 5. Indicator menampilkan informasi analisis pada chart; keputusan dan eksekusi trading tetap dilakukan pengguna.'],['Produk apa yang tersedia?','Saat ini tersedia AURIC GRID V5, AURIC SMC SIGNAL, dan AURIC MOMENTUM. Detail masing-masing dapat dilihat pada halaman produknya.'],['Berapa harga produknya?',`Sewa AURIC GRID V5 ${siteConfig.price} / ${siteConfig.rentalDays} hari, termasuk VPS dan pemasangan. Source code EA tidak termasuk. AURIC SMC SIGNAL dan AURIC MOMENTUM masing-masing ${indicatorPurchase.price}, sekali bayar untuk akses seumur hidup, termasuk full source code untuk penggunaan pribadi.`],['Apakah AURIC menjamin profit?','Tidak. EA dan indikator tidak menghilangkan risiko trading. Signal, momentum, serta hasil pengujian tidak menjamin keuntungan atau performa berikutnya.']];return <section className="section container faq-layout brand-faq" id="faq"><div><SectionLabel number="06">FAQ</SectionLabel><h2>Kenali AURIC<br/><span>lebih dekat.</span></h2><WhatsAppLink message={brand.message} className="inline-link">Tanya admin <Arrow diagonal/></WhatsAppLink></div><div className="faq-list">{items.map(([q,a],i)=><details key={q}><summary><span className="faq-number">0{i+1}</span><span>{q}</span><span className="faq-plus">+</span></summary><p>{a}</p></details>)}</div></section>}
